/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class team_dhuacm_RigidJudge_local_Sandbox */

#ifndef _Included_team_dhuacm_RigidJudge_local_Sandbox
#define _Included_team_dhuacm_RigidJudge_local_Sandbox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     team_dhuacm_RigidJudge_local_Sandbox
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_team_dhuacm_RigidJudge_local_Sandbox_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
