language: java

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install gcc-4.8 -qq
 - sudo apt-get install g++-4.8 -qq
 - gcc-4.8 --version
 - g++-4.8 --version
 - gcc --version
 - g++ --version

notifications:
  slack:
    rooms:
      - algalon:aPdVkFFhzaWZ5OIZRHY3l4nA#rigidoj

