language: java

before_install:
  - sudo apt-get update
  # gcc
  - sudo apt-get install gcc
  - gcc --version
  # g++
  - sudo apt-get install g++
  - g++ --version

notifications:
  slack:
    rooms:
      - algalon:aPdVkFFhzaWZ5OIZRHY3l4nA#rigidoj

